# Generated by Django 4.2 on 2024-03-21 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
