# Generated by Django 4.2 on 2024-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publis_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
