# Generated by Django 4.2 on 2024-03-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_publis_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publis_date',
            new_name='publish_date',
        ),
    ]
