# Generated by Django 4.2 on 2024-03-21 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_publis_date_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
